version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Install buildah"
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qq -y software-properties-common
            sudo add-apt-repository -y ppa:projectatomic/ppa
            sudo apt-get update -qq
            sudo apt-get -qq -y install buildah
      - run:
          name: "Show buildah version"
          command: buildah version
